name: final_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swipable: ^1.2.1 
  android_id: ^0.4.0
  device_info_plus: ^11.2.0
  provider: ^6.0.0
  http: ^1.0.0
  flutter_swiper_null_safety: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true